@startuml

class "<object>"
abstract "<sixty-unit>"
abstract "<time>"
abstract "<angle>"
class "<time-of-day>"
class "<time-offset>"
abstract "<directed-angle>"
class "<relative-angle>"
abstract "<position>"
class "<absolute-position>"
class "<relative-position>"
class "<latitude>"
class "<longitude>"

"<object>" <|-- "<sixty-unit>"
"<object>" <|-- "<position>"
"<sixty-unit>" <|-- "<time>"
"<sixty-unit>" <|-- "<angle>"
"<time>" <|-- "<time-of-day>"
"<time>" <|-- "<time-offset>"
"<angle>" <|-- "<directed-angle>"
"<angle>" <|-- "<relative-angle>"
"<directed-angle>" <|-- "<latitude>"
"<directed-angle>" <|-- "<longitude>" 
"<position>" <|-- "<absolute-position>"
"<position>" <|-- "<relative-position>" 

"<sixty-unit>" : total-seconds : <integer>
"<directed-angle>" : direction : <string>
"<absolute-position>" : latitude : <latitude>
"<absolute-position>" : longitude : <longitude>
"<relative-position>" : distance : <single-float>
"<relative-position>" : angle : <relative-angle>

@enduml